/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package scalesweden;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author Niclas Olsson, Cobton AB
 */
public class ClubSettings extends javax.swing.JInternalFrame {

    /**
     * Creates new form ClubSettings
     */
    public ClubSettings() {
        initComponents();
        setSavedInidicatorOff();
        setAlertOffButton();
        readData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jTextField_Clubnr = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField_ClubName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField_ProtocolDriver = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField_Password = new javax.swing.JTextField();
        jButton_Save = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField_UserId = new javax.swing.JTextField();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jLabel6 = new javax.swing.JLabel();
        jTextField_CompLeader = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField_Location = new javax.swing.JTextField();
        jTextField_AirField = new javax.swing.JTextField();
        jLabel_Saved = new javax.swing.JLabel();

        jDialog1.setModal(true);

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setClosable(true);
        setTitle("Inställningar - Klubb");
        setMaximumSize(new java.awt.Dimension(431, 387));
        setName("setDlg"); // NOI18N
        setPreferredSize(new java.awt.Dimension(350, 387));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Klubbnr:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, -1, -1));

        jTextField_Clubnr.setColumns(4);
        jTextField_Clubnr.setToolTipText("Här anger Du klubbens nr enligt SMFF.");
        jTextField_Clubnr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_ClubnrKeyTyped(evt);
            }
        });
        getContentPane().add(jTextField_Clubnr, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 30, 90, -1));

        jLabel2.setText("Klubbens namn:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 12, -1, -1));

        jTextField_ClubName.setToolTipText("Här anger Du klubbens namn.");
        jTextField_ClubName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_ClubNameKeyTyped(evt);
            }
        });
        getContentPane().add(jTextField_ClubName, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 30, 210, -1));

        jLabel3.setText("Ordinarie protokollförare:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 162, -1, -1));

        jTextField_ProtocolDriver.setToolTipText("Ansvarig protokollförare.");
        jTextField_ProtocolDriver.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_ProtocolDriverKeyTyped(evt);
            }
        });
        getContentPane().add(jTextField_ProtocolDriver, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 183, 309, -1));

        jLabel4.setText("Lösenord för skalaflyg.org:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 266, -1, -1));

        jTextField_Password.setToolTipText("Lösenordet för skala webben.");
        jTextField_Password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_PasswordKeyTyped(evt);
            }
        });
        getContentPane().add(jTextField_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 287, 309, -1));

        jButton_Save.setText("Spara");
        jButton_Save.setToolTipText("");
        jButton_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SaveActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Save, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 80, -1));

        jLabel5.setText("Användarid för skalaflyg.org:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 214, -1, -1));

        jTextField_UserId.setToolTipText("Användarid för skala-webben.");
        jTextField_UserId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_UserIdKeyTyped(evt);
            }
        });
        getContentPane().add(jTextField_UserId, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 235, 309, -1));
        getContentPane().add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 297, -1, -1));

        jLabel6.setText("Ordinarie tävlingsledare:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 110, -1, -1));

        jTextField_CompLeader.setToolTipText("Ansvarig protokollförare.");
        jTextField_CompLeader.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_CompLeaderKeyTyped(evt);
            }
        });
        getContentPane().add(jTextField_CompLeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 131, 309, -1));

        jLabel7.setText("Ort:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 61, -1, -1));

        jLabel8.setText("Flygfält:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 61, -1, -1));

        jTextField_Location.setColumns(4);
        jTextField_Location.setToolTipText("Här anger Du klubbens nr enligt SMFF.");
        jTextField_Location.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_LocationKeyTyped(evt);
            }
        });
        getContentPane().add(jTextField_Location, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 79, 135, -1));

        jTextField_AirField.setToolTipText("Här anger Du klubbens namn.");
        jTextField_AirField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_AirFieldKeyTyped(evt);
            }
        });
        getContentPane().add(jTextField_AirField, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 79, 160, -1));

        jLabel_Saved.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel_Saved.setForeground(new java.awt.Color(51, 255, 0));
        jLabel_Saved.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Saved.setLabelFor(this);
        jLabel_Saved.setText("Sparad");
        jLabel_Saved.setToolTipText("");
        jLabel_Saved.setOpaque(true);
        jLabel_Saved.setPreferredSize(new java.awt.Dimension(51, 25));
        getContentPane().add(jLabel_Saved, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, -1, 25));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setSavedInidicatorOff() {
        jLabel_Saved.setVisible(false);
                
    }

    private void setSavedInidicatorOn() {
        jLabel_Saved.setVisible(true);
    }
    
    private void setAlertOnButton() {
        jButton_Save.setBackground(Color.red);
        jButton_Save.setToolTipText("Du har osparad data. Klicka på mig för att spara.");
        jButton_Save.setEnabled(true);
    }
    
    private void setAlertOffButton() {
        jButton_Save.setBackground(Color.lightGray);
        jButton_Save.setToolTipText("Här klickar Du om det finns något att spara.");
        jButton_Save.setEnabled(false);
    }
    
    private void saveData() {

        Connection connection = null;
        try {
            // create a database connection
            connection = DriverManager.getConnection("jdbc:sqlite:db/scale.db");
            Statement statement = connection.createStatement();
            statement.setQueryTimeout(30);  // set timeout to 30 sec.

            // Delete all records
            int rs;
            rs = statement.executeUpdate("delete from clubsettings;");

            try {
                Thread.sleep(200);
            } catch (InterruptedException e) {
            }

            rs = statement.executeUpdate("INSERT INTO clubsettings (clubnr, clubname, driver, userid, password, airfield, compleader, location) "
                    + "VALUES ('" + jTextField_Clubnr.getText() + "', '" + jTextField_ClubName.getText() + "', '"
                    + jTextField_ProtocolDriver.getText() + "', '" + jTextField_UserId.getText() + "', '"
                    + jTextField_Password.getText() + "', '" + jTextField_AirField.getText() + "', '"
                    + jTextField_CompLeader.getText() + "', '" + jTextField_Location.getText() + "');");

        } catch (SQLException e) {
            // if the error message is "out of memory", 
            // it probably means no database file is found
            System.err.println(e.getMessage());
        } finally {
            try {
                if (connection != null) {

                    setSavedInidicatorOn();  //Inform the user that data has been saved
                    setAlertOffButton();
                    connection.close();
                }
            } catch (SQLException e) {
                // connection close failed.
                System.err.println(e);
            }
        }

    }

    private void readData() {

        Connection connection = null;
        try {
            // create a database connection
            connection = DriverManager.getConnection("jdbc:sqlite:db/scale.db");
            Statement statement = connection.createStatement();
            statement.setQueryTimeout(2);  // set timeout to 30 sec.

            ResultSet rs = statement.executeQuery("select * from clubsettings");
            while (rs.next()) { // Should only contain 1 row of data !
                // read the result set
                jTextField_Clubnr.setText(rs.getString("clubnr"));
                jTextField_ClubName.setText(rs.getString("clubname"));
                jTextField_ProtocolDriver.setText(rs.getString("driver"));
                jTextField_UserId.setText(rs.getString("userid"));
                jTextField_Password.setText(rs.getString("password"));
                jTextField_Location.setText(rs.getString("location"));
                jTextField_AirField.setText(rs.getString("airfield"));
                jTextField_CompLeader.setText(rs.getString("compleader"));

            }
        } catch (SQLException e) {
            // if the error message is "out of memory", 
            // it probably means no database file is found
            System.err.println(e.getMessage());
        } finally {
            try {
                if (connection != null) {
                    connection.close();
                }
            } catch (SQLException e) {
                // connection close failed.
                System.err.println(e);
            }
        }

    }
    
    private void jButton_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SaveActionPerformed
        saveData();
    }//GEN-LAST:event_jButton_SaveActionPerformed

    private void jTextField_ClubnrKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_ClubnrKeyTyped
        setSavedInidicatorOff();    
        setAlertOnButton();
    }//GEN-LAST:event_jTextField_ClubnrKeyTyped

    private void jTextField_ClubNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_ClubNameKeyTyped
        setSavedInidicatorOff();
        setAlertOnButton();
    }//GEN-LAST:event_jTextField_ClubNameKeyTyped

    private void jTextField_LocationKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_LocationKeyTyped
       setSavedInidicatorOff();
       setAlertOnButton();
    }//GEN-LAST:event_jTextField_LocationKeyTyped

    private void jTextField_AirFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_AirFieldKeyTyped
        setSavedInidicatorOff();
        setAlertOnButton();
    }//GEN-LAST:event_jTextField_AirFieldKeyTyped

    private void jTextField_CompLeaderKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_CompLeaderKeyTyped
        setSavedInidicatorOff();
        setAlertOnButton();
    }//GEN-LAST:event_jTextField_CompLeaderKeyTyped

    private void jTextField_ProtocolDriverKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_ProtocolDriverKeyTyped
        setSavedInidicatorOff();
        setAlertOnButton();
    }//GEN-LAST:event_jTextField_ProtocolDriverKeyTyped

    private void jTextField_UserIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_UserIdKeyTyped
        setSavedInidicatorOff();
        setAlertOnButton();
    }//GEN-LAST:event_jTextField_UserIdKeyTyped

    private void jTextField_PasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_PasswordKeyTyped
        setSavedInidicatorOff();
        setAlertOnButton();
    }//GEN-LAST:event_jTextField_PasswordKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton_Save;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_Saved;
    private javax.swing.JTextField jTextField_AirField;
    private javax.swing.JTextField jTextField_ClubName;
    private javax.swing.JTextField jTextField_Clubnr;
    private javax.swing.JTextField jTextField_CompLeader;
    private javax.swing.JTextField jTextField_Location;
    private javax.swing.JTextField jTextField_Password;
    private javax.swing.JTextField jTextField_ProtocolDriver;
    private javax.swing.JTextField jTextField_UserId;
    // End of variables declaration//GEN-END:variables
}
